/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author Borin
 */
public class TelaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTriangulo
     */
    public TelaTriangulo() 
    {
    
        initComponents();
    
        panTipo.setVisible( false ) ;
        panTriangulo.setVisible ( false ) ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sliA = new javax.swing.JSlider();
        sliB = new javax.swing.JSlider();
        sliC = new javax.swing.JSlider();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        panTriangulo = new javax.swing.JPanel();
        lblTriangulo = new javax.swing.JLabel();
        panTipo = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Segmento A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Segmento B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Segmento C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, -1, -1));

        sliA.setMaximum(20);
        sliA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliAStateChanged(evt);
            }
        });
        getContentPane().add(sliA, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 32, -1, -1));

        sliB.setMaximum(20);
        sliB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliBStateChanged(evt);
            }
        });
        getContentPane().add(sliB, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 66, -1, -1));

        sliC.setMaximum(20);
        sliC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliCStateChanged(evt);
            }
        });
        getContentPane().add(sliC, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 108, -1, -1));

        lblA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblA.setText("0");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 24, -1, -1));

        lblB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblB.setText("0");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 66, -1, -1));

        lblC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblC.setText("0");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 108, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Borin\\Pictures\\triangulo-abc(1) (1).jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 386, -1));

        btnVerificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 210, 340, -1));

        lblTriangulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTriangulo.setText("Forma Triangulo ?");

        javax.swing.GroupLayout panTrianguloLayout = new javax.swing.GroupLayout(panTriangulo);
        panTriangulo.setLayout(panTrianguloLayout);
        panTrianguloLayout.setHorizontalGroup(
            panTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(panTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panTrianguloLayout.createSequentialGroup()
                    .addGap(0, 316, Short.MAX_VALUE)
                    .addComponent(lblTriangulo)
                    .addGap(0, 317, Short.MAX_VALUE)))
        );
        panTrianguloLayout.setVerticalGroup(
            panTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(panTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panTrianguloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTriangulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 290, 846, -1));

        lblTipo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTipo.setText("Tipo De Triângulo");

        javax.swing.GroupLayout panTipoLayout = new javax.swing.GroupLayout(panTipo);
        panTipo.setLayout(panTipoLayout);
        panTipoLayout.setHorizontalGroup(
            panTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(panTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panTipoLayout.createSequentialGroup()
                    .addGap(0, 319, Short.MAX_VALUE)
                    .addComponent(lblTipo)
                    .addGap(0, 320, Short.MAX_VALUE)))
        );
        panTipoLayout.setVerticalGroup(
            panTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panTipoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblTipo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, 846, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        
       int a = sliA.getValue ( ) ;
       int b = sliB.getValue ( ) ;
       int c = sliC.getValue ( ) ;
       
       if ( ( Math.abs ( b - c ) < a && a < b + c ) && 
          ( Math.abs ( a - c ) < b && b < a + c ) && 
          ( Math.abs ( a - b ) < c && c < a + b ) )
       {
           
           lblTriangulo.setText( "<html>Forma um triângulo !!!</html>" ) ;
           panTriangulo.setVisible( true ) ;
       
           if ( a != b && a != c && b != c )
           {
               
               lblTipo.setText ( "<html>Forma um triângulo Escaleno !!!</html> " ) ;
               
           }
       
           else if ( ( a == b && b == c && c == a  ) )
           {
               
               lblTipo.setText ( "<html>Forma um triângulo Equilátero !!!</html>" ) ;
               
           }
           
           else
           {
               
               lblTipo.setText ( "<html>Forma um triângulo Isósceles !!!</html>" ) ;
               
               
           }
           
           panTipo.setVisible( true ) ;
           
       }   
       
       else
       {
           
           lblTriangulo.setText( "<html>Não forma um triângulo !!!</html>" ) ;
           panTriangulo.setVisible( true ) ;
       }
       
           
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void sliAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliAStateChanged
        
        lblA.setText ( Integer.toString( sliA.getValue ( ) ) ) ;
        
    }//GEN-LAST:event_sliAStateChanged

    private void sliBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliBStateChanged
        
        lblB.setText ( Integer.toString ( sliB.getValue ( ) ) ) ;
        
    }//GEN-LAST:event_sliBStateChanged

    private void sliCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliCStateChanged
        
        lblC.setText ( Integer.toString( sliC.getValue ( ) ) ) ;
        
    }//GEN-LAST:event_sliCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTriangulo;
    private javax.swing.JPanel panTipo;
    private javax.swing.JPanel panTriangulo;
    private javax.swing.JSlider sliA;
    private javax.swing.JSlider sliB;
    private javax.swing.JSlider sliC;
    // End of variables declaration//GEN-END:variables
}
